language: csharp
os:
 - osx
 - linux
before_install:
 - date -u
 - uname -a
 - export PATH=/opt/mono/bin:$PATH
 - env | sort
install:
  - sudo apt-get install mono-devel mono-gmcs nunit-console
solution: ru.org.openam.dotnet.sln
branches:
 only:
   - master
notifications:
 email:
  - support@openam.org.ru
